live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 12

[font.bold]
family = "Victor Mono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Victor Mono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Victor Mono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 12
y = 10

### Colors ###
[colors.primary]
background = '#232136'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#56526e'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#56526e'

[colors.selection]
text = '#e0def4'
background = '#44415a'
[colors.normal]
black = '#393552'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ea9a97'
white = '#e0def4'

[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ea9a97'
white = '#e0def4'

[colors.hints]
start = { foreground = '#908caa', background = '#2a273f' }
end = { foreground = '#6e6a86', background = '#2a273f' }
