live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 12

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 12
y = 10

### Colors ###
# Default colors
[colors.primary]
background = '#303446' # base
foreground = '#C6D0F5' # text
# Bright and dim foreground colors
dim_foreground = '#C6D0F5' # text
bright_foreground = '#C6D0F5' # text

# Cursor colors
[colors.cursor]
text = '#303446' # base
cursor = '#F2D5CF' # rosewater

[colors.vi_mode_cursor]
text = '#303446' # base
cursor = '#BABBF1' # lavender

# Search colors
[colors.search.matches]
foreground = '#303446' # base
background = '#A5ADCE' # subtext0
[colors.search.focused_match]
foreground = '#303446' # base
background = '#A6D189' # green
[colors.footer_bar]
foreground = '#303446' # base
background = '#A5ADCE' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#303446' # base
background = '#E5C890' # yellow
[colors.hints.end]
foreground = '#303446' # base
background = '#A5ADCE' # subtext0

# Selection colors
[colors.selection]
text = '#303446' # base
background = '#F2D5CF' # rosewater

# Normal colors
[colors.normal]
black = '#51576D' # surface1
red = '#E78284' # red
green = '#A6D189' # green
yellow = '#E5C890' # yellow
blue = '#8CAAEE' # blue
magenta = '#F4B8E4' # pink
cyan = '#81C8BE' # teal
white = '#B5BFE2' # subtext1

# Bright colors
[colors.bright]
black = '#626880' # surface2
red = '#E78284' # red
green = '#A6D189' # green
yellow = '#E5C890' # yellow
blue = '#8CAAEE' # blue
magenta = '#F4B8E4' # pink
cyan = '#81C8BE' # teal
white = '#A5ADCE' # subtext0

# Dim colors
[colors.dim]
black = '#51576D' # surface1
red = '#E78284' # red
green = '#A6D189' # green
yellow = '#E5C890' # yellow
blue = '#8CAAEE' # blue
magenta = '#F4B8E4' # pink
cyan = '#81C8BE' # teal
white = '#B5BFE2' # subtext1
